services:
  postgres:
    image: postgis/postgis:17-master
    platform: linux/amd64
    ports:
      - 54321:5432
    environment:
      POSTGRES_USER: sit-in-spaeti
      POSTGRES_PASSWORD: sit-in-spaeti
      POSTGRES_DB: sit-in-spaeti
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: