[phases.setup]
nixPkgs = ["nodejs_22", "bun", "curl", "wget"]

[phases.install]
cmds = ["bun i --no-save"]

[phases.build]
cmds = ["bun run build"]

[start]
cmd = "bun run db:migrate && bun run start"